services:

  redis:
    image: redis:7
    container_name: notification-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17
    container_name: notification-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notification_user -d notification_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: notification-api
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  notification-worker:
    build: .
    container_name: notification-worker
    command: node src/queue/notificationWorker.js
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  outbox-worker:
    build: .
    container_name: notification-outbox-worker
    command: node src/workers/outboxWorker.js
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

volumes:
  postgres_data: