name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-north-1
  AWS_ACCOUNT_ID: "881490132448"
  ECR_REGISTRY: "881490132448.dkr.ecr.eu-north-1.amazonaws.com"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  docker-build:
    name: Build and Push Docker Images
    needs: test
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::881490132448:role/github-actions-notification-ecr
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push API image
        run: |
          docker build -t notification-api:${{ github.sha }} .
          docker tag notification-api:${{ github.sha }} \
            $ECR_REGISTRY/notification-api:${{ github.sha }}
          docker push \
            $ECR_REGISTRY/notification-api:${{ github.sha }}

      - name: Build and push Notification Worker image
        run: |
          docker build -t notification-worker:${{ github.sha }} .
          docker tag notification-worker:${{ github.sha }} \
            $ECR_REGISTRY/notification-worker:${{ github.sha }}
          docker push \
            $ECR_REGISTRY/notification-worker:${{ github.sha }}

      - name: Build and push Outbox Worker image
        run: |
          docker build -t notification-outbox-worker:${{ github.sha }} .
          docker tag notification-outbox-worker:${{ github.sha }} \
            $ECR_REGISTRY/notification-outbox-worker:${{ github.sha }}
          docker push \
            $ECR_REGISTRY/notification-outbox-worker:${{ github.sha }}

      
      # - name: Render API task definition
      #   id: render-api
      #   uses: aws-actions/amazon-ecs-render-task-definition@v1
      #   with:
      #     task-definition: ecs/api-task-definition.json
      #     container-name: notification-api
      #     image: ${{ env.ECR_REGISTRY }}/notification-api:${{ github.sha }}

      # - name: Deploy API to ECS
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      #   with:
      #     task-definition: ${{ steps.render-api.outputs.task-definition }}
      #     service: notification-api
      #     cluster: notification-cluster
      #     wait-for-service-stability: true